name: CI

on:
  push:
  pull_request:
    branches: ["master", "main", "dev", "development"]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: ruff check
      uses: astral-sh/ruff-action@v3

  unittest:
    runs-on: ubuntu-latest
    defaults:
      run:
        # run a login shell to set the conda environment properly
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yaml
    - name: Run tests
      run: |
        python -m unittest discover -s tests/ -t .
